[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B","C4","SIM","PL"]
ignore = ["E203","E266","E501","W503"]
exclude = [
  ".git",
  ".github",
  "third_party",
  "AXIOMHIVE_ZKVS_SIEVE_PROTOCOL/tests",
]

[tool.pytest.ini_options]
addopts = "-q --tb=short"

[tool.coverage.run]
branch = true
source = [
  "AXIOMHIVE_ZKVS_SIEVE_PROTOCOL/src",
]
omit = [
  "**/tests/**",
]

[tool.coverage.report]
show_missing = true
skip_empty = true
