name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install minimal dependencies
      run: |
        pip install --upgrade pip
        # None needed except pytest (pure Python)
        pip install pytest
    - name: Run tests
      run: pytest -q --tb=short --no-header --maxfail=1
    - name: Archive Test Output (Proof Artifacts)
      uses: actions/upload-artifact@v3
      with:
        name: proof-artifacts
        path: AXIOMHIVE_ZKVS_SIEVE_PROTOCOL/tests/
